DROP TABLE IF EXISTS transactions;


CREATE TABLE transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payer TEXT NOT NULL,
    points INTEGER NOT NULL,
    timestamp_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);